sudo: required

language: haskell

ghc:
- 8.0.1

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.stack/

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal setup
- stack --no-terminal install

script:
- travis_wait stack build --pedantic
- stack haddock
- stack exec tabl-example-users
- stack exec tabl-example-multiply -- 7
- stack exec tabl-example-tictactoe
- stack exec tabl-example-constants
